[package]
name = "rust-doubao-watermark"
version = "1.0.1"
edition = "2024"
description = "豆包 AI 图片去水印命令行工具"
license = "MIT"

[dependencies]
arboard = "3.6.1"
image = "0.25.9"
viuer = { version = "0.11.0", features = ["sixel"] }
